# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Python image
FROM python:3.10-slim as base

# Set the working directory
WORKDIR /app

# Copy the entire repository into the container
COPY . .

# Install the project in editable mode
RUN pip install -e .

# Set the environment variable for the audio directory
# This can be overwritten by providing the AUDIO_PLAYER_DIR environment variable at runtime
ENV AUDIO_PLAYER_DIR=/music

# Expose any ports if needed (for MCP this might not be necessary)

# Define the entrypoint for the container
ENTRYPOINT ["python", "src/audio_player_mcp/player.py"]